### ISSUE TITLE
docs.ansible.com - design is broken

### ISSUE THREAD

**Issue by miketaylr** [webcompat/pretriage-test-issues#26]
**URL**: http://docs.ansible.com/ansible/latest/modules/apt_module.html

**Browser / Version**: Firefox 62.0
**Operating System**: Mac OS X 10.13
**Tested Another Browser**: Yes

**Problem type**: Design is broken
**Description**: Table conent is all mushed together
**Steps to Reproduce**:
Navigated to the URL. Not sure if this is a FF problem or a problem with the Ansible site. It does display correctly in Chrome.
[![Screenshot Description](https://webcompat.com/uploads/2018/5/3c561239-2ed4-4615-80c8-d712335ce615-thumb.jpg)](https://webcompat.com/uploads/2018/5/3c561239-2ed4-4615-80c8-d712335ce615.jpg)

<details>
<summary>Browser Configuration</summary>
<ul>
  <li>buildID: 20180509100510</li><li>gfx.webrender.blob-images: true</li><li>gfx.webrender.all: false</li><li>gfx.webrender.enabled: false</li><li>image.mem.shared: true</li><li>channel: nightly</li>
</ul>
</details>

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by hellosct1** [comment]
Testing in

* Linux (debian / ubuntu / mint)
Nightly 64.0a1 (2018-09-26)  with and without responsive
Firefox 62  with and without responsive
Chromium 65.0.3325.181


* windows 8
Nightly 64.0a1 (2018-09-26) 
Firefox 62  with and without responsive
Chrome Version 69.0.3497.100

* Android 6
Firefox Focus 7.0.5
Firefox 62
Nightly 64.0a1 (2018-09-26) 
Chrome



unable to reproduce the issue
