### ISSUE TITLE
www.fxp.co.il - design is broken

### ISSUE THREAD

**Issue by miketaylr** [webcompat/pretriage-test-issues#27]
**URL**: https://www.fxp.co.il/

**Browser / Version**: Firefox Mobile 62.0
**Operating System**: mi4i miui 9
**Tested Another Browser**: No

**Problem type**: Design is broken
**Description**: design
**Steps to Reproduce**:

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by hellosct1** [comment]
Testing in

* Linux (debian / ubuntu / mint)
                     Nightly 64.0a1 (2018-09-26) with and without responsive
                     Firefox 62 with and without responsive
                     Chromium 65.0.3325.181


* windows 8
                     Nightly 64.0a1 (2018-09-26)  with and without responsive
                     Firefox 62 with and without responsive
                     Chrome Version 69.0.3497.100


* Android 6
                     Firefox Focus 7.0.5
                     Firefox 62
                     Nightly 64.0a1 (2018-09-26) 
                     Chrome

Under Firefox Focus, you can't access the website because of the captcha when all privacy options are enabled.
Which is normal.
