### ISSUE TITLE
web.autocad.com - see bug description

### ISSUE THREAD

**Issue by miketaylr** [webcompat/pretriage-test-issues#75]
**URL**: https://web.autocad.com/#/

**Browser / Version**: Firefox 62.0
**Operating System**: Windows 10
**Tested Another Browser**: Yes

**Problem type**: Something else
**Description**: This website runs on Chrome but doesn't runs on Firefox.
**Steps to Reproduce**:

_From [webcompat.com](https://webcompat.com/) with ❤️_

**Comment by abhiaecs** [comment]
This is a duplicate issue from Bugzilla/Webcompat #74 

![image](https://user-images.githubusercontent.com/10229535/45356253-6d8c1980-b5e0-11e8-9802-caed254342a7.png)
